import { headers } from "next/headers";

import { buildTenantOrigin } from "@/lib/tenant-host";
import { env } from "@/lib/env/server";
import { clientEnv } from "@/lib/env/client";

/**
 * Absolute URLs that follow the REQUEST's host, not the build's (F4.6).
 *
 * ─── Why `absoluteUrl()` could not simply be extended ───────────────────────
 *
 * `src/lib/site.ts` builds on `NEXT_PUBLIC_APP_URL`, which Next inlines at BUILD
 * time. One image therefore carries exactly one origin, which was fine while
 * everything authenticated lived on the apex. Once each academy has its own
 * host, a link built that way sends a signed-in user to a host where their
 * cookie does not exist — and the failure reads as "randomly logged out", not
 * as a URL bug.
 *
 * So this reads the origin from the request instead. Same trade-off `apexUrl()`
 * in src/proxy.ts already makes, for the same reason, from the same inputs:
 * `APP_ROOT_DOMAIN` (a RUNTIME var) plus the served request's protocol and port.
 *
 * `absoluteUrl()` keeps its job — canonical tags, sitemap, robots.txt. Those are
 * apex-only and statically generated, so a request-aware variant would be both
 * wrong and impossible there.
 *
 * The string work lives in `tenant-host.ts` (env-free, unit-tested); this file
 * is only the request plumbing, which is why it holds no logic worth testing in
 * isolation.
 */

/**
 * Absolute URL of `path` on `subdomain`'s host, derived from the current request.
 *
 * For CROSS-ORIGIN links only: the academy directory on the apex, and anything
 * that must return a user to the host they started on. Same-host links stay
 * relative and must NOT come through here — a relative href keeps working when
 * the host changes, an absolute one silently pins the wrong one.
 *
 * Protocol comes from `x-forwarded-proto` when present: the proxy in front of us
 * terminates TLS, so the app's own view of the scheme is `http` in production.
 */
export async function tenantUrl(subdomain: string, path = "/"): Promise<string> {
  const h = await headers();
  const proto = await requestProtocol(h);
  return `${buildTenantOrigin(subdomain, env.APP_ROOT_DOMAIN, h.get("host"), proto)}${path}`;
}

/**
 * Absolute URL of `path` on the platform apex, derived from the current request.
 *
 * Needed wherever an action ENDS a user's relationship with the academy whose
 * host they are on — leaving it, deleting it. `redirect("/dashboard")` there
 * would land on the panel of an academy they are no longer a member of, and the
 * honest answer to that is a 403. The apex dashboard is where they belong.
 *
 * The server-component counterpart to `apexUrl()` in src/proxy.ts. Two small
 * implementations rather than one shared: that one has a `NextRequest` and this
 * one has `headers()`, and threading a fake request through the proxy's version
 * would be more indirection than the four lines it saves.
 */
export async function apexUrl(path = "/"): Promise<string> {
  const h = await headers();
  const proto = await requestProtocol(h);
  const port = hostPortOf(h.get("host"));
  const host = port ? `${env.APP_ROOT_DOMAIN}:${port}` : env.APP_ROOT_DOMAIN;
  return `${proto}//${host}${path}`;
}

/** `https:` behind a TLS-terminating proxy, `http:` in dev. URL-style, with the colon. */
async function requestProtocol(h: Awaited<ReturnType<typeof headers>>): Promise<string> {
  const forwarded = h.get("x-forwarded-proto");
  if (forwarded) return `${forwarded.split(",")[0]!.trim()}:`;
  return env.NODE_ENV === "production" ? "https:" : "http:";
}

/** Port of the incoming Host, or "" — see the port warning in `buildTenantOrigin`. */
function hostPortOf(hostHeader: string | null): string {
  // Reuse the tested rule by round-tripping through the builder rather than
  // writing a third copy of the bracket-aware port split.
  const probe = buildTenantOrigin("x", "y", hostHeader, "http:");
  const match = /:(\d+)$/.exec(probe);
  return match?.[1] ?? "";
}

/**
 * Absolute URL on an academy host WITHOUT a request — for jobs and webhooks.
 *
 * `tenantUrl` reads `headers()`, which throws outside a request scope. Billing
 * notifications, the email fan-out and anything else on the queue run with no
 * request at all, so they need the origin derived from configuration only.
 *
 * Protocol and port come from `NEXT_PUBLIC_APP_URL`, which names the apex. That
 * value is build-time frozen, but only its SCHEME AND PORT are borrowed here —
 * the host itself is rebuilt from the runtime `APP_ROOT_DOMAIN`, so one image
 * still serves every academy. Without the port, links generated by jobs in dev
 * would drop `:3000` and point at nothing.
 */
export function tenantUrlFromEnv(subdomain: string, path = "/"): string {
  const apex = new URL(clientEnv.NEXT_PUBLIC_APP_URL);
  return `${buildTenantOrigin(subdomain, env.APP_ROOT_DOMAIN, apex.host, apex.protocol)}${path}`;
}
